### ISSUE TITLE
[Question] Is it still working?

### ISSUE THREAD

**Issue by ramazansancar** [VinceZK/node-background-job#1]
Questions:
- Is it still running smoothly?
- Will there be an update in Angular version?
- Are you planning to create an area to login to the panel? (Username and password, dealership system etc.)

Thanks :)

**Comment by VinceZK** [comment]
to your questions:
Yes, it is still working. 
Maybe, depends on if there is some valid requirements.
It is already there if you go for https://darkhouse.com.cn/logon

**Comment by VinceZK** [comment]
Closed as answered.

**Comment by ramazansancar** [comment]
> to your questions: Yes, it is still working. Maybe, depends on if there is some valid requirements. It is already there if you go for https://darkhouse.com.cn/logon
So what should I do to include the logon page. I'm not a judge as I haven't used Angular before :/

You've made a repo containing exactly the project I wanted. First of all, thank you for this. I was going to create a series of crawler bots to generate the data for a site, but I needed to think a little more about how to get it to work. This project is exactly as I want, the only problem is that if I go live, I don't need the login screen because the bots' interface can be open to everyone. Thanks in advance
